import { StyleSheet } from "react-native";

export const doctorDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 16,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  backButton: {
    padding: 8,
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E9ECEF',
    elevation: 2,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1F2937",
  },
  doctorProfile: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  doctorDetailImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginRight: 16,
  },
  doctorProfileInfo: {
    flex: 1,
  },
  doctorDetailName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 4,
  },
  doctorDetailSpecialty: {
    fontSize: 16,
    color: '#3CB179',
    marginBottom: 12,
    fontWeight: '500',
  },
  doctorDetailStats: {
    flexDirection: 'row',
    gap: 16,
  },
  doctorStat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  doctorStatText: {
    fontSize: 14,
    color: '#6B7280',
  },
  section: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 12,
  },
  aboutText: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
  },
  readMoreText: {
    fontSize: 14,
    color: '#3CB179',
    fontWeight: '500',
    marginTop: 8,
  },
  datesScroll: {
    marginHorizontal: -5,
  },
  datesContainer: {
    flexDirection: 'row',
    paddingHorizontal: 5,
    gap: 8,
  },
  dateButton: {
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    minWidth: 60,
  },
  selectedDateButton: {
    backgroundColor: '#3CB179',
  },
  dateDayText: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
    marginBottom: 4,
  },
  dateNumberText: {
    fontSize: 16,
    color: '#1F2937',
    fontWeight: 'bold',
  },
  dateMonthText: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 2,
  },
  selectedDateText: {
    color: '#fff',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  timeNoteText: {
    fontSize: 12,
    color: '#6B7280',
    fontStyle: 'italic',
  },
  timeSlotsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  timeSlotButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    minWidth: 100,
    alignItems: 'center',
  },
  selectedTimeSlotButton: {
    backgroundColor: '#3CB179',
  },
  timeSlotText: {
    fontSize: 14,
    color: '#1F2937',
    fontWeight: '500',
  },
  selectedTimeSlotText: {
    color: '#fff',
  },
  noSlotsText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    fontStyle: 'italic',
    padding: 20,
  },
  bookAppointmentButton: {
    backgroundColor: '#3CB179',
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    marginVertical: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  bookAppointmentButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  disabledButton: {
    backgroundColor: '#9CA3AF',
    opacity: 0.6,
  },
});