import { Platform, StatusBar, StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 20,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 20 : 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  title: {
    fontSize: 26,
    lineHeight: 34,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 4,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 18,
    height: 48,
  },
  searchInput: {
    marginLeft: 10,
    flex: 1,
    color: "#111827",
    fontSize: 14,
    paddingVertical: 0,
  },
  categoryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  categoryCard: {
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    paddingVertical: 14,
    width: 78,
    borderRadius: 12,
    justifyContent: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
  },
  categoryText: {
    marginTop: 5,
    fontSize: 12,
    color: "#374151",
  },
  banner: {
    backgroundColor: "#E6F4FE",
    borderRadius: 15,
    flexDirection: "row",
    padding: 15,
    alignItems: "center",
    marginBottom: 18,
  },
  bannerTitle: {
    fontWeight: "600",
    fontSize: 15,
    color: "#111827",
    marginBottom: 10,
  },
  learnMoreButton: {
    backgroundColor: "#3CB179",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignSelf: "flex-start",
  },
  learnMoreText: {
    color: "#fff",
    fontWeight: "600",
  },
  bannerImage: {
    width: 88,
    height: 88,
    resizeMode: "contain",
    marginLeft: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#111827",
  },
  seeAll: {
    color: "#3CB179",
    fontWeight: "500",
  },
  horizontalScroll: {
    marginBottom: 24,
  },
  doctorCard: {
    backgroundColor: "#F9FAFB",
    borderRadius: 15,
    padding: 16,
    alignItems: "center",
    marginRight: 16,
    width: 170,
    minHeight: 180,
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
  },
  doctorImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
    marginBottom: 12,
  },
  doctorName: {
    fontWeight: "600",
    color: "#0F172A",
    textAlign: "center",
    fontSize: 14,
  },
  doctorSpecialty: {
    fontSize: 12,
    color: "#6B7280",
    marginBottom: 8,
  },
  doctorInfoRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  doctorRating: {
    color: "#111827",
    fontSize: 12,
    marginHorizontal: 4,
  },
  doctorDistance: {
    fontSize: 12,
    color: "#6B7280",
  },
  // Updated Article Box Styles with smaller fonts
  articleBox: {
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    padding: 14,
    marginBottom: 22,
  },
  expandedArticleBox: {
    backgroundColor: "#F0F9FF",
  },
  articleHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  articleTitle: {
    fontWeight: "500",
    color: "#111827",
    fontSize: 16,
    flex: 1,
    marginRight: 10,
  },
  articleSummary: {
    color: "#6B7280",
    fontSize: 13,
    lineHeight: 18,
  },
  articleContent: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  articleSubtitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 6,
    marginTop: 10,
  },
  articleBulletPoint: {
    fontSize: 13,
    color: "#374151",
    lineHeight: 18,
    marginBottom: 4,
    marginLeft: 8,
  },
  articleText: {
    fontSize: 13,
    color: "#374151",
    lineHeight: 18,
    marginBottom: 8,
    marginTop: 10,
    fontStyle: 'italic',
  },
});

// Placeholder default export for Expo Router
export default function HomeStylesRoutePlaceholder() { return null; }