import { StyleSheet } from "react-native";

export const findDoctorsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 16,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  backButton: {
    padding: 8,
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E9ECEF',
    elevation: 2,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1F2937",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 20,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 16,
    color: "#1F2937",
  },
  categoriesScroll: {
    marginBottom: 20,
  },
  categoriesRow: {
    flexDirection: "row",
    paddingBottom: 10,
  },
  categoryButton: {
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    marginRight: 10,
    alignItems: "center",
    minWidth: 100,
    flexDirection: "row",
    gap: 8,
  },
  selectedCategoryButton: {
    backgroundColor: "#3CB179",
  },
  categoryButtonText: {
    fontSize: 14,
    color: "#4B5563",
    fontWeight: "500",
  },
  selectedCategoryText: {
    color: "#fff",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1F2937",
  },
  seeAll: {
    fontSize: 14,
    color: "#3CB179",
    fontWeight: "500",
  },
  doctorsList: {
    marginBottom: 20,
  },
  doctorListItem: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  doctorListImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 12,
  },
  doctorInfo: {
    flex: 1,
  },
  doctorName: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#1F2937",
  },
  doctorSpecialty: {
    fontSize: 12,
    color: "#6B7280",
    marginBottom: 4,
  },
  doctorExperience: {
    fontSize: 12,
    color: "#9CA3AF",
    marginBottom: 4,
  },
  doctorInfoRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  doctorRating: {
    fontSize: 12,
    color: "#1F2937",
    marginLeft: 4,
    marginRight: 8,
  },
  doctorDistance: {
    fontSize: 12,
    color: "#6B7280",
    marginLeft: 4,
  },
  bookButton: {
    backgroundColor: "#3CB179",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  bookButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "500",
  },
  recentDoctorCard: {
    alignItems: "center",
    marginRight: 16,
    backgroundColor: "#fff",
    padding: 12,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
    minWidth: 80,
  },
  recentDoctorImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginBottom: 8,
  },
  recentDoctorName: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#1F2937",
    textAlign: "center",
  },
  recentDoctorSpecialty: {
    fontSize: 10,
    color: "#6B7280",
    textAlign: "center",
  },
  horizontalScroll: {
    marginBottom: 20,
  },
});